from django.test import TestCase
from unittest.mock import patch
from django.contrib.auth.models import User
from storybook.models import Story

class AIGenerationTestCase(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(username='ai_user', password='password123')

    def test_ai_assisted_story_flag(self):
        """Test that AI assisted stories are flagged correctly."""
        story = Story.objects.create(
            title="AI Story",
            author=self.user,
            content="This story was generated by AI.",
            creation_type="ai_assisted",
            cover_image="https://example.com/ai-image.jpg"
        )
        
        saved_story = Story.objects.get(id=story.id)
        self.assertEqual(saved_story.creation_type, "ai_assisted")
        self.assertIn("ai-image", saved_story.cover_image)

    @patch('storybook.ai_proxy_views.replicate', autospec=True)
    def test_replicate_mock(self, mock_replicate):
        """Verify that the AI Generation module properly integrates mock generation."""
        # Simple test to verify the mocking framework works for replicate
        mock_replicate.Client.return_value.predictions.create.return_value.id = "mock_prediction_123"
        
        client = mock_replicate.Client(api_token="dummy")
        prediction = client.predictions.create(
            model="black-forest-labs/flux-schnell",
            input={"prompt": "test"}
        )
        
        self.assertEqual(prediction.id, "mock_prediction_123")
