# Generated by Django 4.2.7 on 2025-10-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tl', 'Tagalog')], default='en', max_length=2),
        ),
    ]
