# Generated by Django 4.2.7 on 2025-10-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0003_story_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
