# Generated by Django 4.2.7 on 2025-10-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0004_story_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
