# Generated by Django 4.2.7 on 2025-10-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0005_alter_story_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('action', 'Action'), ('friendship', 'Friendship'), ('scifi', 'Sci-Fi'), ('comedy', 'Comedy'), ('sci_fi', 'Science Fiction'), ('fairy_tale', 'Fairy Tale'), ('educational', 'Educational'), ('animal', 'Animal Stories'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
