# Generated by Django 4.2.7 on 2025-10-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0006_alter_story_category_alter_story_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.URLField(blank=True, default='', max_length=5000),
        ),
    ]
