# Generated by Django 4.2.7 on 2025-10-21 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storybook', '0008_alter_story_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='storybook.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_saved'],
                'unique_together': {('story', 'user')},
            },
        ),
    ]
