# Generated by Django 4.2.7 on 2025-10-21 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storybook', '0009_savedstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='metric_type',
            field=models.CharField(choices=[('published_stories', 'Published Stories Count'), ('total_stories', 'Total Stories Count'), ('friends_count', 'Friends Count'), ('total_words', 'Total Words Written'), ('likes_received', 'Likes Received'), ('comments_received', 'Comments Received'), ('stories_read', 'Stories Read Count'), ('leaderboard_rank', 'Leaderboard Rank'), ('manual_stories', 'Manual Stories Count'), ('ai_stories', 'AI-Assisted Stories Count'), ('collaborative_stories', 'Collaborative Stories Count'), ('characters_created', 'Characters Created Count'), ('story_views', 'Story Views Count'), ('story_downloads', 'Story Downloads Count')], default='published_stories', max_length=30),
        ),
        migrations.AddField(
            model_name='achievement',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('mythic', 'Mythic')], default='common', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='creation_type',
            field=models.CharField(choices=[('manual', 'Manual Creation'), ('ai_assisted', 'AI-Assisted'), ('collaborative', 'Collaborative')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='earned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='is_earned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('published_stories', 'Published Stories'), ('friends', 'Friends & Social'), ('words', 'Word Count'), ('likes', 'Likes Received'), ('comments', 'Comments Received'), ('stories_read', 'Stories Read'), ('leaderboard', 'Leaderboard Rank'), ('creation_type', 'Story Creation'), ('collaboration', 'Collaboration'), ('characters', 'Characters Created')], default='published_stories', max_length=30),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='📖', max_length=10),
        ),
        migrations.CreateModel(
            name='StoryRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_read', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='storybook.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_read', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stories Read',
                'ordering': ['-date_read'],
                'unique_together': {('story', 'user')},
            },
        ),
    ]
