# Generated by Django 4.2.7 on 2025-10-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0010_achievement_metric_type_achievement_rarity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyread',
            options={'ordering': ['-date_read']},
        ),
        migrations.RemoveField(
            model_name='story',
            name='downloads',
        ),
        migrations.RemoveField(
            model_name='storyread',
            name='completed',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('published_stories', 'Published Stories'), ('friends', 'Friends & Social'), ('words', 'Word Count'), ('likes', 'Likes Received'), ('comments', 'Comments Received'), ('stories_read', 'Stories Read'), ('leaderboard', 'Leaderboard Rank'), ('creation_type', 'Creation Type'), ('collaboration', 'Collaboration'), ('characters', 'Characters Created')], default='published_stories', max_length=20),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='📖', max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='metric_type',
            field=models.CharField(choices=[('published_stories', 'Published Stories Count'), ('friends', 'Friends Count'), ('total_words', 'Total Words Written'), ('likes_received', 'Likes Received'), ('comments_received', 'Comments Received'), ('stories_read', 'Stories Read Count'), ('leaderboard_rank', 'Leaderboard Rank'), ('manual_stories', 'Manual Stories Created'), ('ai_stories', 'AI-Assisted Stories Created'), ('collaboration_count', 'Collaboration Count'), ('characters_created', 'Characters Created')], default='published_stories', max_length=30),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='rarity',
            field=models.CharField(default='common', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='creation_type',
            field=models.CharField(choices=[('manual', 'Manual Creation'), ('ai_assisted', 'AI-Assisted')], default='manual', max_length=20),
        ),
    ]
