# Generated by Django 4.2.7 on 2025-11-09 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storybook', '0011_alter_storyread_options_remove_story_downloads_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('canvas_name', models.CharField(default='Untitled Canvas', max_length=200)),
                ('canvas_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('published_stories', 'Published Stories'), ('friends', 'Friends & Social'), ('words', 'Word Count'), ('likes', 'Likes Received'), ('comments', 'Comments Received'), ('stories_read', 'Stories Read'), ('leaderboard', 'Leaderboard Rank'), ('creation_type', 'Creation Type'), ('collaboration', 'Collaboration'), ('characters', 'Characters Created'), ('views', 'Story Views')], default='published_stories', max_length=20),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='metric_type',
            field=models.CharField(choices=[('published_stories', 'Published Stories Count'), ('friends', 'Friends Count'), ('total_words', 'Total Words Written'), ('likes_received', 'Likes Received'), ('comments_received', 'Comments Received'), ('stories_read', 'Stories Read Count'), ('leaderboard_rank', 'Leaderboard Rank'), ('total_stories', 'Total Stories Created'), ('manual_stories', 'Manual Stories Created'), ('ai_stories', 'AI-Assisted Stories Created'), ('collaboration_count', 'Collaboration Count'), ('characters_created', 'Characters Created'), ('views_received', 'Story Views Received')], default='published_stories', max_length=30),
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursor_position', models.JSONField(blank=True, default=dict)),
                ('cursor_color', models.CharField(default='#FF0000', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='storybook.collaborationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('session', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DrawingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('path', 'Path Drawing'), ('shape', 'Shape'), ('text', 'Text'), ('erase', 'Erase'), ('clear', 'Clear Canvas'), ('transform', 'Transform'), ('delete', 'Delete Object')], max_length=20)),
                ('operation_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sequence_number', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='storybook.collaborationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp', 'sequence_number'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='storybook_d_session_120f0a_idx')],
            },
        ),
    ]
