# Generated by Django 4.2.7 on 2025-11-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0012_collaborationsession_alter_achievement_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Request Accepted'), ('story_liked', 'Story Liked'), ('story_commented', 'Story Commented'), ('story_rated', 'Story Rated'), ('achievement_earned', 'Achievement Earned'), ('story_published', 'Story Published'), ('new_message', 'New Message'), ('collaboration_invite', 'Collaboration Invitation')], max_length=30),
        ),
    ]
