# Generated by Django 4.2.7 on 2025-11-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0014_userprofile_is_online_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('collaboration_invite', 'Collaboration Invite')], default='text', max_length=30),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
