# Generated by Django 4.2.7 on 2025-11-16 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storybook', '0015_message_message_type_message_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='collaborationsession',
            name='canvas_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='collaborationsession',
            name='current_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collaborationsession',
            name='is_lobby_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collaborationsession',
            name='last_autosave',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborationsession',
            name='operation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collaborationsession',
            name='story_draft',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='collaborationsession',
            name='voting_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collaborationsession',
            name='voting_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='drawingoperation',
            name='page_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='current_tool',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('participant', 'Participant')], default='participant', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='co_authored_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='collaboration_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_story', to='storybook.collaborationsession'),
        ),
        migrations.AddField(
            model_name='story',
            name='is_collaborative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_collab_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drawingoperation',
            name='operation_type',
            field=models.CharField(choices=[('path', 'Path Drawing'), ('shape', 'Shape'), ('text', 'Text'), ('erase', 'Erase'), ('clear', 'Clear Canvas'), ('transform', 'Transform'), ('delete', 'Delete Object'), ('text_edit', 'Text Edit'), ('page_change', 'Page Change'), ('add_page', 'Add Page'), ('delete_page', 'Delete Page')], max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='creation_type',
            field=models.CharField(choices=[('manual', 'Manual Creation'), ('ai_assisted', 'AI-Assisted'), ('collaborative', 'Collaborative')], default='manual', max_length=20),
        ),
        migrations.AddIndex(
            model_name='drawingoperation',
            index=models.Index(fields=['session', 'page_number'], name='storybook_d_session_f64fe1_idx'),
        ),
        migrations.AddField(
            model_name='collaborationinvite',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_collab_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborationinvite',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_collab_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborationinvite',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='storybook.collaborationsession'),
        ),
        migrations.AlterUniqueTogether(
            name='collaborationinvite',
            unique_together={('session', 'receiver')},
        ),
    ]
