# Generated by Django 4.2.7 on 2025-11-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0017_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_emoji',
            field=models.CharField(blank=True, default='📚', max_length=10),
        ),
    ]
