# Generated by Django 4.2.7 on 2025-11-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0019_profanityword'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationsession',
            name='join_code',
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True, unique=True),
        ),
    ]
