# Generated by Django 4.2.7 on 2025-12-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0024_storygame_gamequestion_gameattempt_gameanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('word_search', 'Word Search')], max_length=20),
        ),
        migrations.AlterField(
            model_name='storygame',
            name='game_type',
            field=models.CharField(choices=[('quiz', 'Multiple Choice Quiz'), ('fill_blanks', 'Fill in the Blanks'), ('word_search', 'Word Search')], max_length=20),
        ),
    ]
