# Generated by Django 4.2.7 on 2025-12-17 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storybook', '0025_alter_gamequestion_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherstudentrelationship',
            name='class_name',
        ),
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('grade_level', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('school_year', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Class',
                'verbose_name_plural': 'Teacher Classes',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='teacherstudentrelationship',
            name='teacher_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='storybook.teacherclass'),
        ),
    ]
