# Generated by Django 4.2.29 on 2026-07-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0028_add_privacy_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationsession',
            name='story_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
